FROM platformatic/node-caged:25-slim

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json* ./
RUN npm install --include=dev

COPY src ./src
COPY .version* ./

EXPOSE 8090

CMD ["npm", "run", "dev-in-docker"]
