version: '3.9'
services:
  plantnet:
    build: .
    command:
      /app/node_modules/.bin/nodemon app/plantnet.js --watch app --watch config -L
    ports:
      - 8090:8090
    volumes:
      - .:/app/
    restart: always
    environment:
      - ENV_ID=dev
    network_mode: bridge
    networks:
      - gratheon
networks:
  gratheon: