version: '3.9'
services:
  plantnet:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8090:8090
    volumes:
      - .:/app/
    restart: always
    environment:
      - ENV_ID=dev
    network_mode: bridge
    networks:
      - gratheon
networks:
  gratheon: