services:
  plantnet:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8090:8090
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./.version:/app/.version
      - /app/node_modules
    restart: always
    environment:
      - ENV_ID=dev
      - NODE_OPTIONS=--enable-source-maps
