FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json* ./
RUN npm install --include=dev

COPY src/config ./src/config
COPY .version* ./

EXPOSE 8090

CMD npm run dev-in-docker
